#!/usr/bin/Rscript
##
## File:    plotALAAMEEvsRandomDegreeDist.R
## Author:  Alex Stivala
## Created: August 2023
##
## Plot some statistics (degree distributions specifically)
## of nodes with ALAAM binary outcome variable equal to 1 in the observed
## outcome vector, and simulated outcome vectors (as generated by
## Python function simulate_from_network_attr(..., outputSimulatedVectors=True)
## and also on the same plot random outcome vectors with same density as
## observed (i.e. same probability of a node being 1, but all independent)
##
##
## Usage: Rscript plotALAAMEEsimFit.R [-o] netfilename obsOutcomefilename simOutcomefilePrefix
##  netfilename is the Pajek format graph as used in ALAAMEE estimation.
##  obsOutcomefilename is the observed binary outcome vectors as used in
##    ALAAMEE estimation.
##  simOoutcomefilePrefix is the prefix of simulated outcome binary veectors
##    from the simulation. These files have _x.txt appended by ALAAMEE 
##    where x is iteration number.
##
##  -o : outdegree only - only do out-degree not in-degree plots for directed
##       network.
##
## Output file is simfitPrefix_vs_random.pdf (where Prefix is the simOutcomefilePrefix).
## WARNING: output file is overwritten
##
## Example:
##    /plotALAAMEEsimFit.R ../data/simulated_n500_bin_cont2/n500_kstar_simulate12750000.txt obs_stats_sim_n500.txt sim_outcome
##
## Uses the igraph library to read Pajek format graph files and
## compute graph statistics:
##
##   Csardi G, Nepusz T: The igraph software package for complex network
##   research, InterJournal, Complex Systems
##   1695. 2006. http://igraph.org
##
##
## Note that ALAAMEE can handle very large graphs, but R and igraph
## can be very slow and may not be able to practically work for larger

library(optparse)

library(igraph)

library(grid)
library(gridExtra)
library(ggplot2)
library(reshape)
library(doBy)
library(scales)


## read in R source file from directory where this script is located
##http://stackoverflow.com/questions/1815606/rscript-determine-path-of-the-executing-script
source_local <- function(fname){
  argv <- commandArgs(trailingOnly = FALSE)
  base_dir <- dirname(substring(argv[grep("--file=", argv)], 8))
  source(paste(base_dir, fname, sep=.Platform$file.sep))
}

source_local('simFitPlots.R')




###
### Main
###


args <- commandArgs(trailingOnly=TRUE)

option_list <- list(
  make_option(c("-o", "--outdegree_only"), action="store_true", default=FALSE,
                 help="only plot out-degree not in-degree for directed networks")
  )
parser <- OptionParser(usage = "%prog [options] netfilename obsOutcomefilename simOutcomeFilePrefix",
                       option_list = option_list)
arguments <- parse_args(parser, positional_arguments = 3)
opt <- arguments$options
args <- arguments$args

outdegree_only <- opt$outdegree_only

netfilename <- args[1]
obsoutcomefilename <- args[2]
simoutcomefileprefix <- args[3]

simvec_glob <- paste(simoutcomefileprefix, "_[0-9]*[.]txt", sep='')
outfilename <- paste(simoutcomefileprefix, "_vs_random.pdf", sep='')

g_obs <- read.graph(netfilename, format="pajek")
## Single column table with header, just get the first (only) column
obs_outcomevec <- read.table(obsoutcomefilename, header = TRUE)[,1]
stopifnot(length(obs_outcomevec) == vcount(g_obs))
V(g_obs)$outcome <- obs_outcomevec

sim_files <- Sys.glob(simvec_glob)
if (length(sim_files) == 0) {
  ## try .gz (compressed) instead
  cat('No .txt files with prefix ', simoutcomefileprefix, ' found, trying .txt.gz instead\n')
  simvec_glob <- paste(simoutcomefileprefix, "_[0-9]*[.]txt.gz", sep='')
  sim_files <- Sys.glob(simvec_glob)
}

cat('Reading ', length(sim_files), ' vectors...\n')
## Single column table with header, just get the first (only) column
system.time(sim_outcomevecs <- lapply(sim_files,
                                      FUN = function(f)
                                        read.table(f, header= TRUE)[,1]))

num_nodes <- vcount(g_obs)
## all simulated vectors must have the same number of elements
stopifnot(length(unique((sapply(sim_outcomevecs, function(v) length(v))))) == 1)
## and it must be the same a the number of nodes in the observed graph
stopifnot(num_nodes == length(sim_outcomevecs[[1]]))


num_sim <- length(sim_outcomevecs)


## Generate list of random outcome vectors
if (is.bipartite(g_obs)) {
  numA <- length(V(g_obs)[type == FALSE])
  pA <- sum(V(g_obs)[type == FALSE]$outcome, na.rm=TRUE) / numA
  cat('pA = ', pA, '\n')
  random_outcomevecsA <- lapply(1:num_sim, function(x)
                               sample(2, size = numA, replace = TRUE,
                                      prob = c(1-pA, pA)) - 1)
  numB <- length(V(g_obs)[type == TRUE])
  pB <- sum(V(g_obs)[type == TRUE]$outcome, na.rm=TRUE) / numB
  cat('pB = ', pB, '\n')
  random_outcomevecsB <- lapply(1:num_sim, function(x)
                               sample(2, size = numB, replace = TRUE,
                                      prob = c(1-pB, pB)) - 1)

  random_outcomevecs <- lapply(1:num_sim, function(i) 
                       c(random_outcomevecsA[[i]], random_outcomevecsB[[i]]))
} else {
  cat("obs num outcome 1 is ", sum(V(g_obs)$outcome), "\n")
  #p <- sum(V(g_obs)$outcome) / vcount(g_obs)
  cat("mean sim num outcome 1 is ", mean(sapply(sim_outcomevecs, sum)) , "\n")
  p <- mean(sapply(sim_outcomevecs, sum)) / vcount(g_obs)
  cat('p = ', p, '\n')
  random_outcomevecs <- lapply(1:num_sim, function(x)
                               sample(2, size = vcount(g_obs), replace = TRUE,
                                      prob = c(1-p, p)) - 1)
  cat("mean random num outcome 1 is ", mean(sapply(random_outcomevecs, sum)) , "\n")
}

## build the list of plots
plotlist <- build_sim_fit_plots(g_obs, obs_outcomevec, sim_outcomevecs,
                                random_outcomevecs, 
                                c("ALAAM", "Random"),
                                outdegree_only = outdegree_only)


###
### Write the plots to PDF
###
cat("writing plots to PDF file ", outfilename, "\n")
pdf(outfilename, onefile=FALSE, paper="special", width=9.9, height=6.6)
system.time(do.call(grid.arrange, plotlist))
dev.off()
